name: Dummy
slug: dummy
access: public
description: This is to test and a boilerplate app.
action:
  button:
    screens: 
    - all
    - unassigned
    listing: 
    - all
    label: Send To Pivotal
