name: Dummy
slug: dummy
access: test

description: "This is to test and a boilerplate app.
Accepts newline"

category: Integration

tags: 
- dummy

developer: 
  name: SupportBee
  email: SupportBee
  twitter: "@supportbee"
  github: SupportBee

action:
  button:
    screens: 
    - all
    - unassigned
    label: Send To Dummy
