name: Salesforce
slug: salesforce
access: public

description: "Pull customer information from Saleforce and see it as a comment on the ticket with a link to the Saleforce page.
Accepts newline"

category: Integration

tags: 
- crm
- salesforce

developer: 
  name: Shaikh Imran
  email: imranshaikh818@gmail.com
  twitter: "@imranshaikh_me"
  github: Imranshaikh
