name: Assign After Reply
slug: assign_after_reply
access: public

description: "Use this app to automatically assign the ticket to the agent that replied to the ticket. You can optionally reassign as assigned ticket if a different agent replies to it."

category: workflow

tags: 
- assign
- reply

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: prateekdayal
  github: prateekdayal

# The following config keys are used by Action Handlers
# Set button 'overlay' to true, if you want to have an overlay
# The valid values for screens are [ticket, all, unassigned, my, groups]
# Remove the following section if you do not want to define Action Handlers
 
action:
  button:
    overlay: false
    screens: 
    - ticket
    - all
    - unassigned
    label: Send To Assign_after_reply
