name: Assign After Reply
slug: assign_after_reply
access: public

description: "Use this app to automatically assign the ticket to the agent that replied to the ticket. You can optionally reassign as assigned ticket if a different agent replies to it."

category: workflow

tags: 
- assign
- reply

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: prateekdayal
  github: prateekdayal

