name: Bigcommerce
slug: bigcommerce
access: public

description: "Pulls in the order information of the customer (based on the email address of the ticket sender) and posts it as a comment on the SupportBee ticket. The app also posts a note on customer's profile in Bigcommerce. The note has a link to the support ticket in SupportBee."

category: Ecommerce

tags: 
- bigcommerce
- ecommerce

developer: 
  name: Bopanna
  email: bops.91@gmail.com
  github: bopanna

