name: Archive_after_reply
slug: archive_after_reply
access: public

description: "This app will help the user to automatically archive answered tickets"

category: Integration

tags: 
- archived
- answered

developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  twitter: "@gagan_bopanna"
  github: bopanna

