name: Archive_after_reply
slug: archive_after_reply
access: public

description: "SupportBee's classic mode. Archive a ticket automatically after replying to it. Once you reply, the ticket is automatically taken off the screen without any extra step"

category: workflow

tags: 
- archived
- answered

developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  twitter: "@gagan_bopanna"
  github: bopanna

