name: PushOver
slug: push_over
access: public

description: "Get Push notifications on your iPhone. A Pushover notification is sent every time there is a new ticket or new replies."

category: notification

tags: 
- iphone
- notification

developer: 
  name: Sravan Reddy
  email: sravfeyn@gmail.com
  twitter: "@sravfeyn"
  github: <@sravfeyn>
