name: "JIRA OnDemand"
slug: jira
access: public

description: "Send ticket details to a JIRA project. The ticket is saved as an issue type you specify on JIRA"

category: project-management

tags:
- jira
- project management

developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: bopanna
 
action:
  button:
    overlay: true
    screens: 
    - ticket
    - all
    - unassigned
    label: Send To JIRA
