name: Jira
slug: jira
access: public

description: "
Creates an issue on Jira!

This app can create an issue on Jira on creation of a Ticket.
Alternatively an agent can selectively create an issue on Jira for a particular ticket in SupportBee Ticket screen.
"

category: integration

tags:
- jira
- project management
- issue tracker

developer: 
  name: SupportBee
  email: SupportBee
  twitter: "@supportbee"
  github: SupportBee

action:
  button:
    overlay: false
    screens:
    - ticket
    label: Send To Jira

