name: Bulk SMS
slug: bulktext
access: public

description: "Get notifications for ticket/reply/comments on via SMS. You will need a bulksms account that you can signup for by visiting http://www.bulksms.com/"

category: notification

tags: 
- sms
- bulksms

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "prateekdayal"
  github: prateekdayal

