name: Campfire
slug: campfire
access: public

description: "

Use this app to post new tickets to campfire!

"

category: notification 

tags:
- campfire
- chat

developer: 
  name: Avinasha
  email: me@avinasha.com
  twitter: "@avishastry"
  github: avinasha
