name: Campfire
slug: campfire
access: public

description: "
Post to campfire!

This app can post to campfire on:

1) Ticket Creation
2) Agent Reply Creation
3) Customer Reply Creation
4) Comment Creation

Also an agent can manually post to campfire from the SupportBee Ticket Screen
"

category: integration

tags:
- campfire
- chat

developer: 
  name: SupportBee
  email: SupportBee
  twitter: "@supportbee"
  github: SupportBee

action:
  button:
    overlay: false
    screens:
    - all
    - unassigned
    label: Send To Campfire

