name: Campfire
slug: campfire
access: public

description: "
Post to campfire!

This app can post to campfire on:

1) Ticket Creation

2) Agent Reply Creation

3) Customer Reply Creation

4) Comment Creation
"

category: notification 

tags:
- campfire
- chat

developer: 
  name: Avinasha
  email: me@avinasha.com
  twitter: "@avishastry"
  github: avinasha
