name: Basecamp_classic
slug: basecamp_classic
access: public

description: "This is to test and a boilerplate app.
Accepts newline"

category: project-management

tags: 
- project management

developer: 
developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: bopanna
 
action:
  button:
    overlay: true
    screens: 
    - ticket
    - unassigned
    label: Send To Basecamp_classic
