name: Trello
slug: trello
access: public

description: "Send your issues to trello"

category: project-management 

tags:
- trello

developer:
  name: Stratos Voukelatos
  email: stratosvoukel@gmail.com
  twitter: "supportbee"
  github: binaryactivist

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Trello
