name: Compose
slug: compose
access: public

description: "
Send a new email from within SupportBee. This app uses your SMTP server to relay the emails
"

category: email 

tags: 
- compose

developer: 
  name: Avinasha S
  email: me@avinasha.com
  twitter: "@avishastry"
  github: avinasha

action:
  button:
    overlay: true
    screens: 
    - ticket
    label: Compose
