development:
  app_platform:
    core_app_base_domain: supportbee.com
    core_app_port:
    core_app_protocol: https
    cloudfront_base_url: http://example.com

test:
  app_platform:
    core_app_base_domain: supportbee.com
    core_app_port:
    core_app_protocol: https
    cloudfront_base_url: http://example.com
