subject: Pivotal
name: Pivotal
slug: pivotal
access: public

description: "
Create a story on Pivotal Tracker!

This app allows an agent to selectively create a story on Pivotal for a particular ticket in SupportBee Ticket screen.
"

category: integration

tags:
- pivotal
- project management

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "@prateekdayal"
  github: prateekdayal

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Pivotal
