subject: Pivotal Tracker 
name: Pivotal Tracker
slug: pivotal
access: public

description: "
Create a story on Pivotal Tracker!

This app allows an agent to selectively create a story in Pivotal Tracker for a particular ticket in SupportBee.
"

category: project-management 

tags:
- pivotal
- project management

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "@prateekdayal"
  github: prateekdayal

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Pivotal
