name: Pipedrive
slug: pipedrive
access: public

description: "Pipedrive: Pipeline software that gets you organized!
Pull customer information from Pipedrive and see it as a comment on the ticket with a link to the Pipedrive page.
The app can also update the customer information in Pipedrive whenever there is a new ticket."

category: crm

tags: 
- crm
- pipedrive

developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: bopanna
